name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print 
        run: |
          echo "Hello World"
          ls -la
          pwd
      - name: Print2
        run: echo "bye"
